name: barcode_scan_web
description: A flutter plugin for scanning 2D barcodes and QRCodes via camera.
version: 2.0.1
homepage: https://github.com/mintware-de/flutter_barcode_reader

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.0

environment: 
  sdk: ">=2.0.0-dev.58.0 <3.0.0" 
  flutter: ^1.10.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: BarcodeScanPlugin
        fileName: barcode_web.dart
  assets:
    - assets/jsqrscanner.nocache.js
    - assets/26096D5C9D4499FC412DE6D557CF4723.cache.js
    - assets/21FCD138CF06B5B490DA7F14DD306C4A.cache.js
    - assets/85EFE2E37A204EA7850A307AF743069B.cache.js
    - assets/compilation-mappings.txt
    - assets/EC0F7217F4BCEF91396A176763786FF0.cache.js
    - assets/F18D8F202F2722AE74CE31DB0E4D35D5.cache.js
    - assets/styles.css