name: barcode_scan_web
description: A flutter plugin for scanning 2D barcodes and QRCodes via camera.
version: 2.0.1
homepage: https://github.com/mintware-de/flutter_barcode_reader

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.0

environment: 
  sdk: ">=2.0.0-dev.58.0 <3.0.0" 
  flutter: ^1.10.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: BarcodeScanPlugin
        fileName: barcode_web.dart
  assets:
    - assets/zxingjs.js
    - assets/requirejs.js
    - assets/adapter.js
    - assets/corejs.js
    - assets/styles.css